name: build-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Set up Redis server
      uses: supercharge/redis-github-action@1.4.0

    - name: Installing protoc-gen-go
      run: |
        sudo apt install protobuf-compiler
        sudo apt install golang-goprotobuf-dev
        go get github.com/golang/protobuf/protoc-gen-go
        go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
        go get -u google.golang.org/grpc
        # echo 'export GOPATH=$HOME/Go' >> $HOME/.bashrc
        # source $HOME/.bashrc
        # echo 'export PATH=$PATH:$GOPATH/bin' >> $HOME/.bashrc
        # source $HOME/.bashrc
        export PATH=$PATH:$GOPATH/bin

    - name: Generating protos
      run: |
        protoc --go-grpc_out=. proto/service.proto
        protoc --go_out=. proto/service.proto


    # - name: Generating protos
    #   run: |
    #     chmod +x ./gen.sh
    #     ./gen.sh
    #     go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

