name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Redis Server in GitHub Actions
      uses: supercharge/redis-github-action@1.4.0

    - name: Generating grpc
      run: |
        chmod +x ./gen.sh
        ./gen.sh

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
