name: build-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Set up Redis server
      uses: supercharge/redis-github-action@1.4.0

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Install grpc-go
      run: |
        go get -u google.golang.org/grpc
        go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
        sudo apt install golang-goprotobuf-dev
        echo 'export PATH=$PATH:$GOPATH/bin' >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Generating grpc
      run: |
        cd generated
        ls -l
        chmod +x ./gen.sh
        ./gen.sh

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
